- name: Install Node.JS via NVM and get npm executable path
  ansible.builtin.include_tasks: install_node.yml

# === Python language server should be installed per-venv ===
# - name: Ensure Python pip3 is installed
#   ansible.builtin.apt:
#     name: python3-pip
#     update_cache: true
#   become: true

# - name: Install Python language server
#   ansible.builtin.pip:
#     name: python-lsp-server
#     executable: /usr/bin/pip3

  ## Debian-based
- block:
  - name: Install clangd (apt)
    ansible.builtin.apt:
      name: "clangd-{{ clangd_version }}"
    become: true

  - name: Register clangd as an alternative
    ansible.builtin.alternatives:
      name: clangd
      path: "/usr/bin/clangd-{{ clangd_version }}"
      link: /usr/bin/clangd
      priority: 100
      state: present
    become: true

  - name: Install shellcheck (apt)
    ansible.builtin.apt:
      name: shellcheck
    become: true

  when: ansible_facts['os_family'] == "Debian"

  ## Arch
- block:
  - name: Install clang (pacman)
    community.general.pacman:
      name: clang
      update_cache: true
    become: true

  - name: Install shellcheck (pacman)
    community.general.pacman:
      name: shellcheck
      update_cache: true
    become: true

  when: ansible_facts['os_family'] == "Archlinux"

- name: Install Node-based language servers
  ansible.builtin.shell:
    cmd: "source {{ nvm_script_path }} && npm install -g {{ item }}"
  loop:
    - bash-language-server
    - vim-language-server
    - yaml-language-server
  args:
    executable: /bin/bash
