- name: Create symbolic link to .vimrc
  ansible.builtin.file:
    src: .vimrc
    dest: "{{ ansible_user_dir }}/.vimrc"
    state: link

- name: Copy plugin files
  ansible.builtin.copy:
    src: plugin/
    dest: "{{ ansible_user_dir }}/.vim/plugin/"

- name: Install vim
  ansible.builtin.apt:
    name: vim

- name: Install plugins
  ansible.builtin.shell:
    cmd: "vim -E -s -u {{ ansible_user_dir }}/.vimrc +'PlugInstall --sync' +qa"
