- name: Clone fzf git repository
  ansible.builtin.git:
    repo: https://github.com/junegunn/fzf.git
    dest: "{{ ansible_user_dir }}/.fzf"
    depth: 1

- name: Install fzf using script
  ansible.builtin.shell:
    cmd: "{{ ansible_user_dir }}/.fzf/install --key-bindings --completion --no-update-rc"
  become_user: "{{ ansible_user | default(ansible_env.USER) }}"
