- name: Install packages block
  block:
    - name: Create temporary downloads directory
      ansible.builtin.tempfile:
        state: directory
        suffix: downloads
      register: tempdir

    - name: Install ripgrep
      ansible.builtin.include_tasks: install_ripgrep.yml
      vars:
        pkg_version: "{{ rg_pkg_version }}"

  always:
    - name: Delete temporary downloads directory
      ansible.builtin.file:
        path: "{{ tempdir.path }}"
        state: absent
