- name: Copy .vimrc
  ansible.builtin.copy:
    src: .vimrc
    dest: "{{ ansible_facts['user_dir'] }}/.vimrc"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0644'

- name: Install vim (apt)
  ansible.builtin.apt:
    name: vim
    update_cache: true
  become: true
  when: ansible_facts['os_family'] == "Debian"

- name: Install vim (pacman)
  community.general.pacman:
    name: vim
    update_cache: true
  become: true
  when: ansible_facts['os_family'] == "Archlinux"

- name: Ensure .vim directory exists
  ansible.builtin.file:
    path: "{{ ansible_facts['user_dir']}}/.vim"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'

- name: Copy plugin files
  ansible.builtin.copy:
    src: plugin/
    dest: "{{ ansible_facts['user_dir'] }}/.vim/plugin/"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'

- name: Install plugins
  ansible.builtin.shell:
    cmd: "vim -E -s -u {{ ansible_facts['user_dir'] }}/.vimrc +'PlugInstall --sync' +qa"
