#   ## Debian-based: TODO
# - block:
#   when: ansible_facts['os_family'] == "Debian"

  ## Arch
- name: Install fd (pacman)
  community.general.pacman:
    name: fd
    update_cache: true
  when: ansible_facts['os_family'] == "Archlinux"
  become: true
