- name: Install packages block
  block:
    - name: Create temporary downloads directory
      ansible.builtin.tempfile:
        state: directory
        suffix: downloads
      register: tempdir
      changed_when: false

    # NOTE: Package versions not used for Arch

    - name: Install ripgrep
      ansible.builtin.include_tasks: install_ripgrep.yml
      vars:
        pkg_version: "{{ rg_version }}"

    - name: Install bat
      ansible.builtin.include_tasks: install_bat.yml
      vars:
        pkg_version: "{{ bat_version }}"

    - name: Install fzf
      ansible.builtin.include_tasks: install_fzf.yml

    - name: Install fd
      ansible.builtin.include_tasks: install_fd.yml

    - name: Install zoxide
      ansible.builtin.include_tasks: install_zoxide.yml

  always:
    - name: Delete temporary downloads directory
      ansible.builtin.file:
        path: "{{ tempdir.path }}"
        state: absent
      changed_when: false
