- name: Set up development environment
  hosts: dev_hosts
  tasks:
    - name: Setup vim
      ansible.builtin.include_role:
        name: vim_setup

    - name: Install packages
      ansible.builtin.include_role:
        name: install_packages

    - name: Install language servers
      ansible.builtin.include_role:
        name: install_language_servers

    - name: Set up bat themes
      ansible.builtin.include_role:
        name: setup_bat_themes

    - name: Set up .bashrc
      ansible.builtin.include_role:
        name: setup_bashrc
